[package]
name = "intent_aware_rl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
derive_builder = "0.12.0"
rand = "0.8.5"
